### PR TITLE
Thermometer text formatting update

### PR DESCRIPTION
**Pull request by arh4uwe**
I changed the size of the thermometer label text from 16pt 20pt. I also made the thermometer label text bold. In addition, I changed the color of the thermometer number text to white. Originally, it was only white on Android, and it was black in the web browsers.

### CODE REVIEW

**Comment by kevinsullivan** [comment]
Yay, Amanda. Good job.

**Comment by arh4uwe** [comment]
I can't create a new pull request since there is already an active pull request between the main branch of my fork and the main branch of the original repo. So, accepting this pull request will also incorporate the change in the Dockerfile into the original repo.

**Changes:** The Dockerfile now installs git-lfs. This allows for every file on GitHub to be downloaded into the container when `git checkout` is performed. Before, only some files would be downloaded, which meant the program couldn't be run or tested since crucial files were missing.

**Remaining issues:** Most of the branches are not appearing when `git branch --list` is performed. The only two that are appearing are 1) the main branch, and 2) docker-malformed, a branch I created locally while troubleshooting the container issues and then pushed to GitHub. In other words, the only branch originally from GitHub that I can checkout to is main.

**Comment by kevinsullivan** [comment]
Needs review by Nick.

**Comment by nicholasphair** [comment]
Hi @arh4uwe,

We should merge this soon but we'll need to narrow the changes down. The PR is for updating the text size and color, so we should make sure only the file changes that do that are in this requrest. From what I can see, that means the only changes we want in the PR are in `moraldistress/lib/thermometer/view/themometer_slider.dart` and `moraldistress/lib/thermometer/view/thermometer_view.dart`. 

Can you open up a new PR with only those changes? I would just fetch Kevin's main branch, branch off of that, add your changes, commit, and submit a new request.

**Comment by arh4uwe** [comment]
I tried fetching Professor Sullivan's main branch, but it didn't get rid of all of the other additions I've added. Even if I did another pull request from the branch I've just created, it would still contain all of my updates to the Dockerfile, the infrastructure site, the unit tests, the OpenAPI template, etc.

**Pull request closed without merging**
